# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

services:
  api:
    image: q10taskmanagerapi
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      CONNECTION_STRING: "Host=postgres;Port=15432;Database=TaskManagerDB;User Id=postgres;Password=postgres_password123"
    build:
      context: .
      dockerfile: api.Dockerfile
    ports:
      - 5100:80
    networks:
      - taskmanager-network      
  postgres:
    image: postgres:latest
    container_name: taskmanager-postgres
    environment:
      POSTGRES_DB: TaskManagerDB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres_password123
    ports:
      - "15432:5432"
    # volumes:
    #   - postgres_data:/var/lib/postgresql/data
    networks:
      - taskmanager-network
volumes:
  postgres_data:
networks:
  taskmanager-network:
    driver: bridge      